# Generated by Django 4.1.9 on 2023-06-28 17:13

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6, verbose_name='Gender')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('single parent', 'Single Parent')], max_length=13, verbose_name='Martial Status')),
                ('home_address', models.TextField(verbose_name='Home Address')),
                ('mobile_number', models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')], verbose_name='Mobile Number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.employee_photo_file_path, verbose_name='Photo')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('bank_branch', models.CharField(max_length=255, verbose_name='Bank Branch')),
                ('bank_account_name', models.CharField(max_length=255, verbose_name='Bank account name')),
                ('bank_account_number', models.CharField(max_length=255, verbose_name='Bank account number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract')], max_length=10, verbose_name='Employment Type')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Is Staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('general', 'General'), ('emergency', 'Emergency')], max_length=10, verbose_name='Loan Type')),
                ('loan_date', models.DateField(auto_now=True, verbose_name='Loan date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount')),
                ('monthly_installment', models.PositiveIntegerField(default=1, verbose_name='Monthly Installment')),
                ('due', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Due')),
                ('remain', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Remain')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('not approved', 'Not-approved')], max_length=15, verbose_name='Action')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partial paid', 'Partial Paid'), ('not paid', 'Not Paid')], default='not paid', max_length=50, verbose_name='Loan Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Role name')),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('permissions', models.ManyToManyField(to='auth.permission')),
                ('user', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Payment day')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('loan', models.ManyToManyField(related_name='loans', to='core.loan')),
                ('user', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pay_Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loan', models.PositiveBigIntegerField(verbose_name='Total loan')),
                ('deduction', models.PositiveBigIntegerField(verbose_name='Deduction')),
                ('basic_salary', models.PositiveBigIntegerField(verbose_name='Basic Salary')),
                ('profit', models.PositiveBigIntegerField(verbose_name='Profit')),
                ('tax', models.PositiveBigIntegerField(verbose_name='Tax')),
                ('payment_date', models.DateField(verbose_name='Payment date')),
                ('net_salary', models.PositiveBigIntegerField(verbose_name='Net Salary')),
                ('user', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Department name')),
                ('details', models.TextField(verbose_name='Department Details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Branch name')),
                ('address', models.TextField(verbose_name='Branch address')),
                ('details', models.TextField(verbose_name='Branch details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='basic_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to='core.pay_roll'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
